# App\Entity\Product:
#     properties:
#         name:
#             - NotBlank:
#                 message: 'Le nom du produit est obligatoire'
#             - Length:
#                 min: 3
#                 max: 255
#                 minMessage : 'Le nom du produit doit faire + de 3'
#         price:
#             - NotBlank:
#                 message: 'le prix est obligatoire'
